# This Document explain about GNU/Emacs and How to Install Emacs on Linux, Emacs Command list.
* GNU/Emacs:
- Emacs stands for Editing Macros, It was created by GNU project founder Richard Stallman. Which is the most popular and powerful text editor available today. It is widely used mainly on Unix-based systems by programmers, scientists, engineers, students, and system administrators. Like other Unix text editors, Emacs provides typed commands and special key combinations, that let you add, delete, insert, and otherwise manipulate words, letters, lines, and other units of text. Emacs is commonly used to enter the source statements for programs. Emacs itself is built using the Lisp programming language.
** Features of Emacs:
+ It can support many languages like Python, HTML, CSS, Shell etc.
+ It can supports most Unix-like systems (GNU/Linux, the various BSDs, Solaris, AIX, HP-UX, IRIX, etc.), DOS, Microsoft Windows, Mac OS X
+ Emacs includes special features to help you write in many different human languages and programming/markup languages
  As well as tools for compiling, running, and testing programs.
+ Emacs can read news, mail, and RSS feeds
+ All of the basic editing commands are available no matter what you're trying to do: write code, read a manual, use a shell, or compose an email.
+ All the tools Emacs provides for opening, saving, searching, and processing text (and more) are available to you no matter what you're doing.
** Install Emacs:
- To install emacs on linux using given following command.
  + On Ubuntu/Debian
#+begin_example
apt-get install emacs
#+end_example
  + On CentOS/RHEL
#+begin_example
yum install emacs
#+begin_example

*** How to Run Emacs:
- To start emacs type emacs or emacs -nw for commandline version
#+begin_example
Ex:= emacs or emacs -nw
#+end_example
*** Emacs Commands List :
- For more Commands Information to Click this Link for Emacs Reference Card-page which is available at [[https://www.gnu.org/software/emacs/refcards/pdf/refcard.pdf][here]]
C = Control
M = Meta = Alt|Esc
